# Generated by Django 5.0 on 2023-12-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'SUPERADMIN'), (2, 'ADMINISTRATOR'), (3, 'CUSTOMER'), (4, 'SUPPLIER')], verbose_name={1: 1, 2: 2, 3: 3, 4: 4}),
        ),
    ]
